  /// \file EventAction.h
/*
 *
 * EventAction.h header template automatically generated by a class generator
 * Creation date : mar. juil. 8 2014
 *
 * This file is part of TpcSDHCALSim libraries.
 * 
 * TpcSDHCALSim is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * TpcSDHCALSim is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with TpcSDHCALSim.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi
 * @copyright CNRS , IPNL
 */


#ifndef EVENTACTION_H
#define EVENTACTION_H

#include "G4UserEventAction.hh"


namespace tpc_sdhcal
{

/** 
 * @brief EventAction class
 */ 
class EventAction : public G4UserEventAction 
{
 public:

 EventAction();
 virtual ~EventAction();

 void BeginOfEventAction(const G4Event *pEvent);
 void EndOfEventAction(const G4Event *pEvent);

}; 

} 

#endif  //  EVENTACTION_H
