  /// \file PrimaryGeneratorAction.h
/*
 *
 * PrimaryGeneratorAction.h header template automatically generated by a class generator
 * Creation date : mar. juil. 8 2014
 *
 * This file is part of TpcSDHCALSim libraries.
 * 
 * TpcSDHCALSim is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * TpcSDHCALSim is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with TpcSDHCALSim.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi
 * @copyright CNRS , IPNL
 */


#ifndef PRIMARYGENERATORACTION_H
#define PRIMARYGENERATORACTION_H

#include "G4VUserPrimaryGeneratorAction.hh"

class G4ParticleGun;

namespace tpc_sdhcal
{

/** 
 * @brief PrimaryGeneratorAction class
 */ 
class PrimaryGeneratorAction : public G4VUserPrimaryGeneratorAction 
{
public:

 PrimaryGeneratorAction();
 virtual ~PrimaryGeneratorAction();

 void GeneratePrimaries(G4Event* pEvent);

protected:

 G4ParticleGun     *m_pParticleGun;
}; 

} 

#endif  //  PRIMARYGENERATORACTION_H
