  /// \file TrackingAction.h
/*
 *
 * TrackingAction.h header template automatically generated by a class generator
 * Creation date : mar. juil. 8 2014
 *
 * This file is part of TpcSDHCALSim libraries.
 * 
 * TpcSDHCALSim is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * TpcSDHCALSim is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with TpcSDHCALSim.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi
 * @copyright CNRS , IPNL
 */


#ifndef TRACKINGACTION_H
#define TRACKINGACTION_H

#include "G4UserTrackingAction.hh"


namespace tpc_sdhcal
{

/** 
 * @brief TrackingAction class
 */ 
class TrackingAction : public G4UserTrackingAction 
{
public:

 TrackingAction();
 virtual ~TrackingAction();

 virtual void PreUserTrackingAction(const G4Track*);
 virtual void PostUserTrackingAction(const G4Track*);

}; 

} 

#endif  //  TRACKINGACTION_H
