  /// \file PrimaryGeneratorAction.cc
/*
 *
 * PrimaryGeneratorAction.cc source template automatically generated by a class generator
 * Creation date : mar. juil. 8 2014
 *
 * This file is part of TpcSDHCALSim libraries.
 * 
 * TpcSDHCALSim is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * TpcSDHCALSim is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with TpcSDHCALSim.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi
 * @copyright CNRS , IPNL
 */


#include "PrimaryGeneratorAction.h"

//geant4
#include "G4ParticleGun.hh"

// std
#include <stddef.h>

namespace tpc_sdhcal
{

PrimaryGeneratorAction::PrimaryGeneratorAction() :
		m_pParticleGun(NULL)
{
	m_pParticleGun = new G4ParticleGun();
}

PrimaryGeneratorAction::~PrimaryGeneratorAction() 
{
	delete m_pParticleGun;
}


void PrimaryGeneratorAction::GeneratePrimaries(G4Event* pEvent)
{
	m_pParticleGun->GeneratePrimaryVertex(pEvent);
}

} 

